//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfLanzamientoObjeto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseDeDatosSorrySlidersEntities : DbContext
    {
        public BaseDeDatosSorrySlidersEntities()
            : base("name=BaseDeDatosSorrySlidersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<Cuenta> CuentaSet { get; set; }
        public virtual DbSet<Partida> PartidaSet { get; set; }
        public virtual DbSet<RelacionBaneados> RelacionBaneadosSet { get; set; }
        public virtual DbSet<RelacionPartidaCuenta> RelacionPartidaCuentaSet { get; set; }
        public virtual DbSet<RelaciónAmigos> RelaciónAmigosSet { get; set; }
    }
}
