//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfLanzamientoObjeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelaciónAmigos
    {
        public int IdRelaciónAmigos { get; set; }
        public string CorreoElectrónicoJugadorPrincipal { get; set; }
        public string CorreoElectrónicoJugadorAmigo { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Cuenta Cuenta1 { get; set; }
    }
}
